hr_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views

admin.AdminSite.site_header = 'Payroll System Administration'
admin.AdminSite.site_title = 'Payroll System Admin'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('logout_reset/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_RESET_REDIRECT_URL), name='reset_logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/auth/password_reset.html',
                                              email_template_name='users/auth/password_reset_email.html'),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/auth/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/auth/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('payroll.urls')),
    path('users/', include('users.urls')),
    path('support_data/', include('support_data.urls')),
    path('admin/', views.login_admin),
    path('admin/payroll/', admin.site.urls),
    path('reports/', include('reports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

payroll/urls.py
from django.urls import path

from . import views
from .views import (PayrollCenterCreate, PayrollCenterUpdate, PayrollCenterListView, PayrollCenterDetailView,
                    PayrollPeriodCreate, PayrollPeriodDetailView, PayrollPeriodListView, PayrollPeriodUpdate,
                    PayrollPeriodForProcessing, LSTListView, PayrollPeriodCloseListView, PayrollCenterStaffListView,
                    EarningAndDeductionCreate, EarningAndDeductionUpdate, EarningAndDeductionDetailView,
                    EarningAndDeductionListView, BankCreate, BankUpdate, BankDetailView, BankListView,
                    PayrollCenterEdsCreate, PayrollCenterEdsUpdate, PayrollCenterEdsDetailView,
                    PayrollCenterEdsListView, CurrencyCreate, CurrencyUpdate, CurrencyDetailView, CurrencyListView)

app_name = 'payroll'
urlpatterns = [
    path('', views.index, name='index'),
    path('payroll/payroll_center/add/', PayrollCenterCreate.as_view(), name='payroll-center-create'),
    path('payroll/payroll_center/<int:pk>/edit/', PayrollCenterUpdate.as_view(), name='payroll-center-update'),
    path('payroll/payroll_center/', PayrollCenterListView.as_view(), name='payroll-center-list'),
    path('payroll/payroll_center/<int:pk>/', PayrollCenterDetailView.as_view(), name='payroll-center-detail'),
    path('payroll/payroll_period/add/', PayrollPeriodCreate.as_view(), name='payroll-period-create'),
    path('payroll/payroll_period/<int:pk>/edit/', PayrollPeriodUpdate.as_view(), name='payroll-period-update'),
    path('payroll/payroll_period/', PayrollPeriodListView.as_view(), name='payroll-period-list'),
    path('payroll/payroll_period/<int:pk>/', PayrollPeriodDetailView.as_view(), name='payroll-period-detail'),
    path('payroll/payroll_period/open', PayrollPeriodForProcessing.as_view(), name='open-payroll-period-list'),
    path('payroll/payroll_period/close', PayrollPeriodCloseListView.as_view(), name='close-payroll-period-list'),
    path('payroll/payroll_period/close/<int:pk>', views.close_payroll_period, name='close-payroll-period'),
    path('payroll/earning_and_deductions/add/', EarningAndDeductionCreate.as_view(), name='ed-type-create'),
    path('payroll/earning_and_deduction/<int:pk>/edit/', EarningAndDeductionUpdate.as_view(), name='ed-type-update'),
    path('payroll/earning_and_deductions/', EarningAndDeductionListView.as_view(), name='ed-type-list'),
    path('payroll/earning_and_deduction/<int:pk>/', EarningAndDeductionDetailView.as_view(), name='ed-type-detail'),
    path('payroll/payroll_center_eds/add/', PayrollCenterEdsCreate.as_view(), name='payroll-center-eds-create'),
    path('payroll/payroll_center_ed<int:pk>/edit/', PayrollCenterEdsUpdate.as_view(), name='payroll-center-eds-update'),
    path('payroll/payroll_center_eds/', PayrollCenterEdsListView.as_view(), name='payroll-center-eds-list'),
    path('payroll/payroll_center_ed/<int:pk>/', PayrollCenterEdsDetailView.as_view(), name='payroll-center-eds-detail'),
    path('payroll/lst/', LSTListView.as_view(), name='lst-list'),
    path('currencies/add/', CurrencyCreate.as_view(), name='currency-create'),
    path('currency<int:pk>/edit/', CurrencyUpdate.as_view(), name='currency-update'),
    path('currencies/', CurrencyListView.as_view(), name='currency-list'),
    path('currency/<int:pk>/', CurrencyDetailView.as_view(), name='currency-detail'),
    path('banks/add/', BankCreate.as_view(), name='bank-create'),
    path('bank<int:pk>/edit/', BankUpdate.as_view(), name='bank-update'),
    path('banks/', BankListView.as_view(), name='bank-list'),
    path('bank/<int:pk>/', BankDetailView.as_view(), name='bank-detail'),
    path('payroll/payroll_center/staff/', PayrollCenterStaffListView.as_view(), name='payroll-center-staff-list'),
]

reports/urls.py
from django.urls import path, include

from . import views

app_name = 'reports'
urlpatterns = [
    path('summary_report/<int:pk>', views.display_summary_report, name='display-summary-report'),
    path('update_summary_report/<int:pp>/<int:user>', views.update_summary_report, name='update-summary-report'),
    path('generate_reports/', views.generate_reports, name='generate-reports'),
    path('reconciliation_report/', views.generate_reconciliation_report, name='generate_reconciliation_report'),
    path('generate_reports/<int:pp>/<int:user>', views.generate_payslip_report, name='generate-payslip'),
    path('email/payslips/', views.send_mass_mail, name='email-payslip'),
]

support_data/urls.py
from django.urls import path

from . import views
from .views import OrganizationCreate, OrganizationListView, OrganizationUpdate, OrganizationDetailView, \
    OrganizationDelete, TaxBracketCreate, TaxBracketUpdate, TaxBracketListView, TaxBracketDetailView, \
    CountryOriginCreate, CountryOriginUpdate, CountryOriginDetailView, CountryOriginListView, \
    NationalityCreate, NationalityUpdate, NationalityDetailView, NationalityListView, \
    DutyStationCreate, DutyStationUpdate, DutyStationDetailView, DutyStationListView, \
    DepartmentCreate, DepartmentUpdate, DepartmentDetailView, DepartmentListView, \
    JobTitleCreate, JobTitleUpdate, JobTitleDetailView, JobTitleListView, \
    ContractTypeCreate, ContractTypeUpdate, ContractTypeDetailView, ContractTypeListView, \
    GradeCreate, GradeUpdate, GradeDetailView, GradeListView, TerminationReasonCreateView, TerminationReasonUpdateView, \
    TerminationReasonListView

app_name = 'support_data'
urlpatterns = [
    path('organizations/add/', OrganizationCreate.as_view(), name='organization-create'),
    path('organization/<int:pk>/edit', OrganizationUpdate.as_view(), name='organization-update'),
    path('organizations/', OrganizationListView.as_view(), name='organization-list'),
    path('organization/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('organization/<int:pk>/delete/', OrganizationDelete.as_view(), name='organization-delete'),
    path('tax_brackets/add/', TaxBracketCreate.as_view(), name='tax-bracket-create'),
    path('tax_bracket<int:pk>/edit/', TaxBracketUpdate.as_view(), name='tax-bracket-update'),
    path('tax_brackets/', TaxBracketListView.as_view(), name='tax-bracket-list'),
    path('tax_bracket/<int:pk>/', TaxBracketDetailView.as_view(), name='tax-bracket-detail'),
    path('country_of_origin/add/', CountryOriginCreate.as_view(), name='country-create'),
    path('country_of_origin<int:pk>/edit/', CountryOriginUpdate.as_view(), name='country-update'),
    path('countries_of_origin/', CountryOriginListView.as_view(), name='country-list'),
    path('country_of_origin/<int:pk>/', CountryOriginDetailView.as_view(), name='country-detail'),
    path('nationalities/add/', NationalityCreate.as_view(), name='nationality-create'),
    path('nationality<int:pk>/edit/', NationalityUpdate.as_view(), name='nationality-update'),
    path('nationalities/', NationalityListView.as_view(), name='nationality-list'),
    path('nationality/<int:pk>/', NationalityDetailView.as_view(), name='nationality-detail'),
    path('duty_stations/add/', DutyStationCreate.as_view(), name='duty-station-create'),
    path('duty_station<int:pk>/edit/', DutyStationUpdate.as_view(), name='duty-station-update'),
    path('duty_stations/', DutyStationListView.as_view(), name='duty-station-list'),
    path('duty_station/<int:pk>/', DutyStationDetailView.as_view(), name='duty-station-detail'),
    path('departments/add/', DepartmentCreate.as_view(), name='department-create'),
    path('department<int:pk>/edit/', DepartmentUpdate.as_view(), name='department-update'),
    path('departments/', DepartmentListView.as_view(), name='department-list'),
    path('department/<int:pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    path('job_titles/add/', JobTitleCreate.as_view(), name='job-title-create'),
    path('job_title<int:pk>/edit/', JobTitleUpdate.as_view(), name='job-title-update'),
    path('job_titles/', JobTitleListView.as_view(), name='job-title-list'),
    path('job_title/<int:pk>/', JobTitleDetailView.as_view(), name='job-title-detail'),
    path('contract_types/add/', ContractTypeCreate.as_view(), name='contract-type-create'),
    path('contract_type<int:pk>/edit/', ContractTypeUpdate.as_view(), name='contract-type-update'),
    path('contract_types/', ContractTypeListView.as_view(), name='contract-type-list'),
    path('contract_type/<int:pk>/', ContractTypeDetailView.as_view(), name='contract-type-detail'),
    path('grades/add/', GradeCreate.as_view(), name='grade-create'),
    path('grade<int:pk>/edit/', GradeUpdate.as_view(), name='grade-update'),
    path('grades/', GradeListView.as_view(), name='grade-list'),
    path('grade/<int:pk>/', GradeDetailView.as_view(), name='grade-detail'),
    path('separation_reason/add/', TerminationReasonCreateView.as_view(), name='reason-create'),
    path('separation_reason<int:pk>/edit/', TerminationReasonUpdateView.as_view(), name='reason-update'),
    path('separation_reason/', TerminationReasonListView.as_view(), name='reason-list'),
    path('send_approval_request/<int:period_id>/', views.send_mail_to_approvers, name='request-approval'),
    path('approve_payroll/<int:period_id>/', views.sign_off_payroll_summary, name='approve_payroll'),
    path('decline_payroll/', views.decline_payroll_summary, name='decline_payroll'),
    path('check_approval_status/<int:period_id>/', views.checkout_for_approval_status, name='approval_status')
]

users/urls.py
from django.urls import path

from . import views
from .views import RecruitedEmployeeListView, ApprovedEmployeeListView, \
    SeparatedEmployeesListView, RejectedEmployeeListView, EmployeeBirthdayList, AssignProjectListView, \
    CostCentreCreate, CostCentreUpdate, CostCentreDetailView, CostCentreListView, \
    SOFCreate, SOFUpdate, SOFDetailView, \
    SOFListView, DEACreate, DEAUpdate, DEADetailView, DEAListView, EmployeeProjectsListView, \
    EmployeeProjectsDetailView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryListView, \
    ProjectCreate, ProjectUpdate, ProjectDetailView, ProjectListView, EmployeeProjectCreation, \
    ChangeGroupEmployeeListView, EmployeeMovementsListView, EmployeeMovementsCreate, ApprovedEmployeeMovementsListView, \
    EnumerationsMovementsCreate, EnumEmployeeMovementsListView

app_name = 'users'
urlpatterns = [
    path('new_employee/', views.register_employee, name='new-employee'),
    path('profile/', views.profile, name='user-profile'),
    path('<int:pk>/edit_employee/', views.user_update_profile, name='user-detail'),
    path('new_employee_approval/', RecruitedEmployeeListView.as_view(), name='employee-approval'),
    path('edit_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_approved_employee_list.html'),
         name='edit-employee'),
    path('terminate_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_terminate_employee_list.html'),
         name='terminate-employee-list'),
    path('separated_employees/', SeparatedEmployeesListView.as_view(), name='separated-employee'),
    path('rejected_employees/', RejectedEmployeeListView.as_view(), name='rejected-employee-list'),
    path('employees_birthdays/', EmployeeBirthdayList.as_view(), name='employee-birthday-list'),
    path('reject_employee/<int:pk>/', views.reject_employee, name='reject-employee'),
    path('new_employee_approval/<int:pk>/edit/', views.approve_employee, name='approve-employee'),
    path('payroll_period/<int:pk>/process/', views.process_payroll_period, name='process_payroll-period'),
    path('payroll_period/<int:pk>/process/<int:user>', views.process_payroll_period, name='process_payroll-period'),
    path('terminate_employee/<int:pk>/', views.terminate_employee, name='terminate-employee'),
    path('employee/assign/projects/', AssignProjectListView.as_view(), name='employee-assign-project'),
    path('employee/assign/project/<int:pk>/', EmployeeProjectCreation.as_view(), name='employee-project-creation'),
    path('cost_centres/add/', CostCentreCreate.as_view(), name='cost-centre-create'),
    path('cost_centre/<int:pk>/edit/', CostCentreUpdate.as_view(), name='cost-centre-update'),
    path('cost_centres/', CostCentreListView.as_view(), name='cost-centre-list'),
    path('cost_centre/<int:pk>/', CostCentreDetailView.as_view(), name='cost-centre-detail'),
    path('projects/add/', ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('sof/add/', SOFCreate.as_view(), name='sof-create'),
    path('sof/<int:pk>/edit/', SOFUpdate.as_view(), name='sof-update'),
    path('sof/', SOFListView.as_view(), name='sof-list'),
    path('sof/<int:pk>/', SOFDetailView.as_view(), name='sof-detail'),
    path('dea/add/', DEACreate.as_view(), name='dea-create'),
    path('dea/<int:pk>/edit/', DEAUpdate.as_view(), name='dea-update'),
    path('dea/', DEAListView.as_view(), name='dea-list'),
    path('dea/<int:pk>/', DEADetailView.as_view(), name='dea-detail'),
    path('employee/projects/', EmployeeProjectsListView.as_view(), name='employee-project-list'),
    path('employee/project/<int:pk>', EmployeeProjectsDetailView.as_view(), name='employee-project-detail'),
    path('employee_category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('employee_category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('employee_categories/', CategoryListView.as_view(), name='category_list'),
    path('employee_category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('change_user_group/<int:pk>', views.user_change_group, name='user_change_group'),
    path('change/group/', ChangeGroupEmployeeListView.as_view(), name='change_employee_user_group'),
    path('employee/reactivate/<int:pk>', views.reactivate_employee, name='reactivate_employee'),
    path('employee/', ApprovedEmployeeMovementsListView.as_view(), name='employee_movements'),
    path('employee/movements/', EmployeeMovementsListView.as_view(), name='employee_movements_changelist'),
    path('employee/movements/add/<int:user_id>/<int:requester_id>/', EmployeeMovementsCreate.as_view(), name='employee_movements_add'),
    path('ajax/load_movements/', views.load_movements, name='ajax_load_movements'),
    path('ajax/load_current_param/', views.load_current_param, name='ajax_load_current'),
    path('employee/earnings/movements/add/<int:user_id>/<int:requester_id>/', EnumerationsMovementsCreate.as_view(),
         name='employee_movements_add_enums'),
    path('employee/earning/movements/', EnumEmployeeMovementsListView.as_view(), name='employee_movements_enums'),
    path('ajax/load_earnings/amount/', views.load_earnings_current_amount, name='ajax_load_current_earning'),
    path('approve/movement/<int:movement_id>/', views.approve_employee_movement, name='approve_employee_movement'),
    path('decline/movement/<int:movement_id>/', views.decline_employee_movement, name='decline_employee_movement'),
    path('ajax/load_overtime_factor/factor/', views.load_overtime_factor, name='ajax_load_factor'),
]

templates/partials/botton_navigation_bar.html
<nav id="bottom-nav" class="my-css navbar navbar-expand-lg navbar-light bg-light py-2 shadow">
    <a class="navbar-brand ml-10" href="{% url 'payroll:index' %}">
        <img src="/media/logo.png" class="img-fluid" style="width: 2em; height: 2em">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown action">
                <a class="nav-link dropdown-header" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Staff <span class="sr-only">(current)</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:new-employee' %}">Add New Employee</a>
                    <a class="dropdown-item" href="{% url 'users:edit-employee' %}">Edit Employee</a>
                    <a class="dropdown-item" href="{% url 'users:rejected-employee-list' %}">Rejected New Employee</a>
                    <a class="dropdown-item" href="{% url 'users:separated-employee' %}">Separated Employees</a>
                    <a class="dropdown-item" href="{% url 'users:terminate-employee-list' %}">Terminate Employee</a>
                    <a class="dropdown-item" href="{% url 'users:employee-assign-project' %}">Assign Employee
                        Projects</a>
                    <a class="dropdown-item" href="{% url 'users:employee-project-list' %}">Employee Projects</a>
                    <a class="dropdown-item" href="{% url 'users:employee-birthday-list' %}">Employee Birthdays</a>
                    <a class="dropdown-item" href="{% url 'users:change_employee_user_group' %}">Change User Group</a>
                </div>
            </li>
            <li class="nav-item dropdown action">
                <a class="nav-link dropdown-header" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Movements
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:employee-approval' %}">New Employee Approval</a>
                    <a class="dropdown-item" href="{% url 'users:employee_movements' %}">Employee Movements Entry</a>
                    <a class="dropdown-item" href="{% url 'users:employee_movements_enums' %}">Salary/Earnings
                        Movements</a>
                    <a class="dropdown-item" href="{% url 'users:employee_movements_changelist' %}">Employee Movements
                        Approval</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-header" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Payroll
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'payroll:payroll-period-create' %}">
                        <small>Add Payroll Period</small>
                    </a>
                    <a class="dropdown-item" href="{% url 'payroll:close-payroll-period-list' %}">
                        <small>Close Payroll Period</small>
                    </a>
                    <a class="dropdown-item" href="{% url 'payroll:open-payroll-period-list' %}">
                        <small>Process Payroll</small>
                    </a>
                    <a class="dropdown-item" href="{% url 'payroll:payroll-period-list' %}">
                        <small>Edit Payroll</small>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-header" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Reports
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'reports:generate-reports' %}">
                        <small>Payroll Reports</small>
                    </a>
                    <a class="dropdown-item" href="{% url 'reports:generate_reconciliation_report' %}">
                        <small>Reconciliation Report</small>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-header" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Support Data
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="dropdown-multicol">
                        <div style="border-left: none">
                            <a class="dropdown-item" href="{% url 'support_data:country-list' %}">Country of Origin</a>
                            <a class="dropdown-item" href="{% url 'support_data:nationality-list' %}">Nationality</a>
                            <a class="dropdown-item" href="{% url 'support_data:duty-station-list' %}">Duty Station</a>
                            <a class="dropdown-item" href="{% url 'support_data:department-list' %}">Departments</a>
                            <a class="dropdown-item" href="{% url 'support_data:job-title-list' %}">Job Titles</a>
                            <a class="dropdown-item" href="{% url 'support_data:contract-type-list' %}">Contract
                                Types</a>
                            <a class="dropdown-item" href="{% url 'users:category_create' %}">Add Staff Category</a>
                            <a class="dropdown-item" href="{% url 'users:category_list' %}">Edit Staff Categories</a>
                        </div>
                        <div class="wider">
                            <a class="dropdown-item" href="{% url 'support_data:organization-create' %}">
                                Add Organization
                            </a>
                            <a class="dropdown-item" href="{% url 'support_data:organization-list' %}">Edit
                                Organization</a>
                            <a class="dropdown-item" href="{% url 'payroll:payroll-center-create' %}">Add Payroll
                                Center</a>
                            <a class="dropdown-item" href="{% url 'payroll:payroll-center-list' %}">Edit Payroll
                                Center</a>
                            <a class="dropdown-item" href="{% url 'payroll:ed-type-create' %}">
                                Add Earning and Deductions
                            </a>
                            <a class="dropdown-item" href="{% url 'payroll:ed-type-list' %}">
                                Edit Earning and Deductions
                            </a>
                            <a class="dropdown-item" href="{% url 'payroll:payroll-center-eds-create' %}">
                                Add Payroll Center Earning and Deductions
                            </a>
                            <a class="dropdown-item" href="{% url 'payroll:payroll-center-eds-list' %}">
                                Edit Payroll Center Earning and Deductions
                            </a>
                        </div>
                        <div>
                            <a class="dropdown-item" href="{% url 'payroll:bank-list' %}">Bank</a>
                            <a class="dropdown-item" href="{% url 'payroll:currency-list' %}">Currencies</a>
                            <a class="dropdown-item" href="{% url 'support_data:grade-list' %}">Grade</a>
                            <a class="dropdown-item" href="{% url 'payroll:payroll-center-staff-list' %}">
                                Payroll Center Staff</a>

                            <a class="dropdown-item" href="{% url 'support_data:reason-list' %}">
                                Separation Reason
                            </a>
                        </div>
                        <div>
                            {#                            TAX SETTINGS #}
                            <a class="dropdown-item dropdown-header"
                               style="font-weight: bolder; color: rgba(93,97,99,0.83);">
                                Tax Settings
                            </a>
                            <a class="dropdown-item" href="{% url 'support_data:tax-bracket-create' %}">
                                Add Tax Bracket
                            </a>
                            <a class="dropdown-item" href="{% url 'support_data:tax-bracket-list' %}">
                                Edit Tax Bracket
                            </a>
                            <a class="dropdown-item" href="{% url 'payroll:lst-list' %}">
                                Edit LST Rates
                            </a>
                        </div>
                        <div>
                            <a class="dropdown-item dropdown-header"
                               style="font-weight: bolder; color: rgba(93,97,99,0.83);">
                                Email Messages
                            </a>
                            <a class="dropdown-item" href="#">
                                Birthday Messages
                            </a>

                            {#                            EMPLOYEE PROJECTS#}
                            <a class="dropdown-item dropdown-header"
                               style="font-weight: bolder; color: rgba(93,97,99,0.83);">
                                Staff Projects
                            </a>
                            <a class="dropdown-item" href="{% url 'users:cost-centre-list' %}">
                                Cost Centres
                            </a>
                            <a class="dropdown-item" href="{% url 'users:project-list' %}">
                                Projects
                            </a>
                            <a class="dropdown-item" href="{% url 'users:sof-list' %}">
                                SOFs
                            </a>
                            <a class="dropdown-item" href="{% url 'users:dea-list' %}">
                                DEAs
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link dropdown-header" href="#">Submit Feedback</a>
            </li>
        </ul>
    </div>
</nav>

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/pagination.html
<div class="d-flex flex-row justify-content-end">
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-primary mb-4"
               href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
</div>