hr_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views

admin.AdminSite.site_header = 'Payroll System Administration'
admin.AdminSite.site_title = 'Payroll System Admin'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('logout_reset/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_RESET_REDIRECT_URL), name='reset_logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/auth/password_reset.html',
                                              email_template_name='users/auth/password_reset_email.html'),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/auth/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/auth/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('payroll.urls')),
    path('users/', include('users.urls')),
    path('support_data/', include('support_data.urls')),
    path('admin/', views.login_admin),
    path('admin/payroll/', admin.site.urls),
    path('reports/', include('reports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

payroll/urls.py
from django.urls import path

from . import views
from .views import (PayrollCenterCreate, PayrollCenterUpdate, PayrollCenterListView, PayrollCenterDetailView,
                    PayrollPeriodCreate, PayrollPeriodDetailView, PayrollPeriodListView, PayrollPeriodUpdate,
                    PayrollPeriodForProcessing, LSTListView, PayrollPeriodCloseListView, PayrollCenterStaffListView,
                    EarningAndDeductionCreate, EarningAndDeductionUpdate, EarningAndDeductionDetailView,
                    EarningAndDeductionListView, BankCreate, BankUpdate, BankDetailView, BankListView,
                    PayrollCenterEdsCreate, PayrollCenterEdsUpdate, PayrollCenterEdsDetailView,
                    PayrollCenterEdsListView, CurrencyCreate, CurrencyUpdate, CurrencyDetailView, CurrencyListView)

app_name = 'payroll'
urlpatterns = [
    path('', views.index, name='index'),
    path('payroll/payroll_center/add/', PayrollCenterCreate.as_view(), name='payroll-center-create'),
    path('payroll/payroll_center/<int:pk>/edit/', PayrollCenterUpdate.as_view(), name='payroll-center-update'),
    path('payroll/payroll_center/', PayrollCenterListView.as_view(), name='payroll-center-list'),
    path('payroll/payroll_center/<int:pk>/', PayrollCenterDetailView.as_view(), name='payroll-center-detail'),
    path('payroll/payroll_period/add/', PayrollPeriodCreate.as_view(), name='payroll-period-create'),
    path('payroll/payroll_period/<int:pk>/edit/', PayrollPeriodUpdate.as_view(), name='payroll-period-update'),
    path('payroll/payroll_period/', PayrollPeriodListView.as_view(), name='payroll-period-list'),
    path('payroll/payroll_period/<int:pk>/', PayrollPeriodDetailView.as_view(), name='payroll-period-detail'),
    path('payroll/payroll_period/open', PayrollPeriodForProcessing.as_view(), name='open-payroll-period-list'),
    path('payroll/payroll_period/close', PayrollPeriodCloseListView.as_view(), name='close-payroll-period-list'),
    path('payroll/payroll_period/close/<int:pk>', views.close_payroll_period, name='close-payroll-period'),
    path('payroll/earning_and_deductions/add/', EarningAndDeductionCreate.as_view(), name='ed-type-create'),
    path('payroll/earning_and_deduction/<int:pk>/edit/', EarningAndDeductionUpdate.as_view(), name='ed-type-update'),
    path('payroll/earning_and_deductions/', EarningAndDeductionListView.as_view(), name='ed-type-list'),
    path('payroll/earning_and_deduction/<int:pk>/', EarningAndDeductionDetailView.as_view(), name='ed-type-detail'),
    path('payroll/payroll_center_eds/add/', PayrollCenterEdsCreate.as_view(), name='payroll-center-eds-create'),
    path('payroll/payroll_center_ed<int:pk>/edit/', PayrollCenterEdsUpdate.as_view(), name='payroll-center-eds-update'),
    path('payroll/payroll_center_eds/', PayrollCenterEdsListView.as_view(), name='payroll-center-eds-list'),
    path('payroll/payroll_center_ed/<int:pk>/', PayrollCenterEdsDetailView.as_view(), name='payroll-center-eds-detail'),
    path('payroll/lst/', LSTListView.as_view(), name='lst-list'),
    path('currencies/add/', CurrencyCreate.as_view(), name='currency-create'),
    path('currency<int:pk>/edit/', CurrencyUpdate.as_view(), name='currency-update'),
    path('currencies/', CurrencyListView.as_view(), name='currency-list'),
    path('currency/<int:pk>/', CurrencyDetailView.as_view(), name='currency-detail'),
    path('banks/add/', BankCreate.as_view(), name='bank-create'),
    path('bank<int:pk>/edit/', BankUpdate.as_view(), name='bank-update'),
    path('banks/', BankListView.as_view(), name='bank-list'),
    path('bank/<int:pk>/', BankDetailView.as_view(), name='bank-detail'),
    path('payroll/payroll_center/staff/', PayrollCenterStaffListView.as_view(), name='payroll-center-staff-list'),
]

reports/urls.py
from django.urls import path, include

from . import views

app_name = 'reports'
urlpatterns = [
    path('summary_report/<int:pk>', views.display_summary_report, name='display-summary-report'),
    path('update_summary_report/<int:pp>/<int:user>', views.update_summary_report, name='update-summary-report'),
    path('generate_reports/', views.generate_reports, name='generate-reports'),
    path('reconciliation_report/', views.generate_reconciliation_report, name='generate_reconciliation_report'),
    path('generate_reports/<int:pp>/<int:user>', views.generate_payslip_report, name='generate-payslip'),
    path('email/payslips/', views.send_mass_mail, name='email-payslip'),
]

users/urls.py
from django.urls import path

from . import views
from .views import RecruitedEmployeeListView, ApprovedEmployeeListView, \
    SeparatedEmployeesListView, RejectedEmployeeListView, EmployeeBirthdayList, AssignProjectListView, \
    CostCentreCreate, CostCentreUpdate, CostCentreDetailView, CostCentreListView, \
    SOFCreate, SOFUpdate, SOFDetailView, \
    SOFListView, DEACreate, DEAUpdate, DEADetailView, DEAListView, EmployeeProjectsListView, \
    EmployeeProjectsDetailView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryListView, \
    ProjectCreate, ProjectUpdate, ProjectDetailView, ProjectListView, EmployeeProjectCreation, \
    ChangeGroupEmployeeListView, EmployeeMovementsListView, EmployeeMovementsCreate, ApprovedEmployeeMovementsListView, \
    EnumerationsMovementsCreate, EnumEmployeeMovementsListView

app_name = 'users'
urlpatterns = [
    path('new_employee/', views.register_employee, name='new-employee'),
    path('profile/', views.profile, name='user-profile'),
    path('<int:pk>/edit_employee/', views.user_update_profile, name='user-detail'),
    path('new_employee_approval/', RecruitedEmployeeListView.as_view(), name='employee-approval'),
    path('edit_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_approved_employee_list.html'),
         name='edit-employee'),
    path('terminate_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_terminate_employee_list.html'),
         name='terminate-employee-list'),
    path('separated_employees/', SeparatedEmployeesListView.as_view(), name='separated-employee'),
    path('rejected_employees/', RejectedEmployeeListView.as_view(), name='rejected-employee-list'),
    path('employees_birthdays/', EmployeeBirthdayList.as_view(), name='employee-birthday-list'),
    path('reject_employee/<int:pk>/', views.reject_employee, name='reject-employee'),
    path('new_employee_approval/<int:pk>/edit/', views.approve_employee, name='approve-employee'),
    path('payroll_period/<int:pk>/process/', views.process_payroll_period, name='process_payroll-period'),
    path('payroll_period/<int:pk>/process/<int:user>', views.process_payroll_period, name='process_payroll-period'),
    path('terminate_employee/<int:pk>/', views.terminate_employee, name='terminate-employee'),
    path('employee/assign/projects/', AssignProjectListView.as_view(), name='employee-assign-project'),
    path('employee/assign/project/<int:pk>/', EmployeeProjectCreation.as_view(), name='employee-project-creation'),
    path('cost_centres/add/', CostCentreCreate.as_view(), name='cost-centre-create'),
    path('cost_centre/<int:pk>/edit/', CostCentreUpdate.as_view(), name='cost-centre-update'),
    path('cost_centres/', CostCentreListView.as_view(), name='cost-centre-list'),
    path('cost_centre/<int:pk>/', CostCentreDetailView.as_view(), name='cost-centre-detail'),
    path('projects/add/', ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('sof/add/', SOFCreate.as_view(), name='sof-create'),
    path('sof/<int:pk>/edit/', SOFUpdate.as_view(), name='sof-update'),
    path('sof/', SOFListView.as_view(), name='sof-list'),
    path('sof/<int:pk>/', SOFDetailView.as_view(), name='sof-detail'),
    path('dea/add/', DEACreate.as_view(), name='dea-create'),
    path('dea/<int:pk>/edit/', DEAUpdate.as_view(), name='dea-update'),
    path('dea/', DEAListView.as_view(), name='dea-list'),
    path('dea/<int:pk>/', DEADetailView.as_view(), name='dea-detail'),
    path('employee/projects/', EmployeeProjectsListView.as_view(), name='employee-project-list'),
    path('employee/project/<int:pk>', EmployeeProjectsDetailView.as_view(), name='employee-project-detail'),
    path('employee_category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('employee_category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('employee_categories/', CategoryListView.as_view(), name='category_list'),
    path('employee_category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('change_user_group/<int:pk>', views.user_change_group, name='user_change_group'),
    path('change/group/', ChangeGroupEmployeeListView.as_view(), name='change_employee_user_group'),
    path('employee/reactivate/<int:pk>', views.reactivate_employee, name='reactivate_employee'),
    path('employee/', ApprovedEmployeeMovementsListView.as_view(), name='employee_movements'),
    path('employee/movements/', EmployeeMovementsListView.as_view(), name='employee_movements_changelist'),
    path('employee/movements/add/<int:user_id>/<int:requester_id>/', EmployeeMovementsCreate.as_view(), name='employee_movements_add'),
    path('ajax/load_movements/', views.load_movements, name='ajax_load_movements'),
    path('ajax/load_current_param/', views.load_current_param, name='ajax_load_current'),
    path('employee/earnings/movements/add/<int:user_id>/<int:requester_id>/', EnumerationsMovementsCreate.as_view(),
         name='employee_movements_add_enums'),
    path('employee/earning/movements/', EnumEmployeeMovementsListView.as_view(), name='employee_movements_enums'),
    path('ajax/load_earnings/amount/', views.load_earnings_current_amount, name='ajax_load_current_earning'),
    path('approve/movement/<int:movement_id>/', views.approve_employee_movement, name='approve_employee_movement'),
    path('decline/movement/<int:movement_id>/', views.decline_employee_movement, name='decline_employee_movement'),
    path('ajax/load_overtime_factor/factor/', views.load_overtime_factor, name='ajax_load_factor'),
]

payroll/forms.py
from django import forms

from .models import PayrollPeriod, PayrollCenter


class PayrollPeriodCreationForm(forms.ModelForm):

    status = forms.CharField(initial='OPEN', disabled=True)

    class Meta:
        model = PayrollPeriod
        fields = ['payroll_center', 'month', 'year', 'status', 'processing_dollar_rate']

templates/payroll/bank_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'payroll:bank-list' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/payroll/currency_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section text-left">
        <h3 class="border-bottom mb-4">Currency</h3>
        Currency: <p style="font-weight: bold">{{ object.currency }}</p>
        Description: <p style="font-weight: bold">{{ object.description }}</p>
        <a class="btn btn-success" href="{% url 'payroll:currency-list' %}">
            BACK
        </a>
    </div>
{% endblock content %}

templates/payroll/currency_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'payroll:currency-list' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/payroll/currency_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Currencies</h4>
        <div class="d-flex flex-row-reverse">
            <div class="p-2">
                <a class="btn btn-success btn-md" href="{% url 'payroll:currency-create' %}">Create</a>
            </div>
        </div>
        <div class="table-responsive-md">
            <table id="table_id" class="table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Currencies</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Currency</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for currency in object_list %}
                    <tr>
                        <td>{{ currency.currency }}</td>
                        <td>{{ currency.description }}</td>
                        <td class="text-primary">
                            <a class="btn btn-primary btn-sm"
                               href="{% url 'payroll:currency-detail' pk=currency.pk %}">View</a>
                            <a class="btn btn-warning btn-sm"
                               href="{% url 'payroll:currency-update' pk=currency.pk %}">Edit</a>
                            <a class="btn btn-danger btn-sm"
                               href="#">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}

templates/payroll/earningdeductiontype_detail.html
{% extends 'payroll/../base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section text-left">
        <h3 class="border-bottom mb-4">Earning and Deduction</h3>
        Name: <p style="font-weight: bold">{{ object.ed_type }}</p>
        Category: <p style="font-weight: bold">{{ object.ed_category }}</p>
        Description: <p style="font-weight: bold">{{ object.description }}</p>
        Recurrent: <p style="font-weight: bold">{{ object.recurrent }}</p>
        Taxable: <p style="font-weight: bold">{{ object.taxable }}</p>
        Account code: <p style="font-weight: bold">{{ object.account_code }}</p>
        Account name: <p style="font-weight: bold">{{ object.account_name }}</p>
        Factor: <p style="font-weight: bold">{{ object.factor }}</p>
        Agresso type: <p style="font-weight: bold">{{ object.agresso_type }}</p>
        Debit/Credit sign: <p style="font-weight: bold">{{ object.debit_credit_sign }}</p>
        Export: <p style="font-weight: bold">{{ object.export }}</p>
        Summarize: <p style="font-weight: bold">{{ object.summarize }}</p>
    </div>
    <a class="btn btn-success" href="{% url 'payroll:ed-type-update' pk=object.id %}">EDIT</a>
    <a class="btn btn-danger" href="{% url 'payroll:ed-type-list' %}">CANCEL</a>
{% endblock content %}

templates/payroll/earningdeductiontype_form.html
{% extends 'payroll/../base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create/ Edit Earning and Deduction</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'payroll:ed-type-list' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/payroll/earningdeductiontype_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Earning and Deductions</h4>
        <div class="table-responsive">
            <table id="table_id" class="table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Earning and Deductions</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Recurrent</th>
                    <th>Taxable</th>
                    <th>Account code</th>
                    <th>Account name</th>
                    <th>Debit/Credit sign</th>
                    <th>Agresso type</th>
                    <th>Factor</th>
                    <th>Export</th>
                    <th>Summarize</th>
                </tr>
                </thead>
                <tbody>
                {% for ed_type in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'payroll:ed-type-update' ed_type.id %}">{{ ed_type.ed_type }}</a>
                        </td>
                        <td>{{ ed_type.description }}</td>
                        <td>{{ ed_type.ed_category }}</td>
                        <td>{{ ed_type.recurrent }}</td>
                        <td>{{ ed_type.taxable }}</td>
                        <td>{{ ed_type.account_code }}</td>
                        <td>{{ ed_type.account_name }}</td>
                        <td>{{ ed_type.debit_credit_sign }}</td>
                        <td>{{ ed_type.agresso_type }}</td>
                        <td>{{ ed_type.factor }}</td>
                        <td>{{ ed_type.export }}</td>
                        <td>{{ ed_type.summarize }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}

templates/payroll/payroll_center_staff_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Payroll centers</h4>
        <div class="d-flex flex-row-reverse">
            <div class="p-2">
                <a class="btn btn-success btn-md" href="{% url 'payroll:payroll-center-create' %}">Create</a>
            </div>
        </div>
        <div class="table-responsive">
            <table id="table_id" class="table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Payroll centers</caption>
                <thead class="thead-dark">
                <tr>

                    <th>Country</th>
                    <th>Payroll Center</th>
                    <th>No. of Staff</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for payroll_center in object_list %}
                    <tr>
                        <td>{{ payroll_center.name }}</td>
                        <td>{{ payroll_center.country }}</td>
                        <td>{{ payroll_center.employee_set.count }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm"
                               href="{% url 'payroll:payroll-center-detail' payroll_center.pk %}">View</a>
                            <a class="btn btn-warning btn-sm"
                               href="{% url 'payroll:payroll-center-update' payroll_center.pk %}">Edit</a>
                            <a class="btn btn-danger btn-sm" href="">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}

templates/payroll/payrollcenter_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'payroll:payroll-center-list' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/payroll/payrollcenter_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Payroll centers</h4>
        <div class="d-flex flex-row-reverse">
            <div class="p-2">
                <a class="btn btn-success btn-md" href="{% url 'payroll:payroll-center-create' %}">Create</a>
            </div>
        </div>
        <div class="table-responsive-md">
            <table id="table_id" class="table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Payroll centers</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Payroll Center</th>
                    <th>Country</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for payroll_center in object_list %}
                    <tr>
                        <td>{{ payroll_center.name }}</td>
                        <td>{{ payroll_center.country }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm"
                               href="{% url 'payroll:payroll-center-detail' payroll_center.pk %}">View</a>
                            <a class="btn btn-warning btn-sm"
                               href="{% url 'payroll:payroll-center-update' payroll_center.pk %}">Edit</a>
                            <a class="btn btn-danger btn-sm" href="">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}

templates/payroll/payrollcentereds_detail.html
{% extends 'payroll/../base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section text-left">
        <h3 class="border-bottom mb-4">Payroll center Earnings and Deductions</h3>
        Payroll center: <p style="font-weight: bold">{{ object.payroll_center }}</p>
        Earning and deduction type: <p style="font-weight: bold">{{ object.ed_type }}</p>
    </div>
    <a class="btn btn-success" href="{% url 'payroll:payroll-center-eds-update' pk=object.id %}">EDIT</a>
    <a class="btn btn-danger" href="{% url 'payroll:payroll-center-eds-list' %}">CANCEL</a>
{% endblock content %}

templates/payroll/payrollcentereds_form.html
{% extends 'payroll/../base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create/ Edit Payroll center Earning and Deduction</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'payroll:payroll-center-eds-list' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}