hr_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views

admin.AdminSite.site_header = 'Payroll System Administration'
admin.AdminSite.site_title = 'Payroll System Admin'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('logout_reset/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_RESET_REDIRECT_URL), name='reset_logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/auth/password_reset.html',
                                              email_template_name='users/auth/password_reset_email.html'),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/auth/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/auth/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('payroll.urls')),
    path('users/', include('users.urls')),
    path('support_data/', include('support_data.urls')),
    path('admin/', views.login_admin),
    path('admin/payroll/', admin.site.urls),
    path('reports/', include('reports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

users/urls.py
from django.urls import path

from . import views
from .views import RecruitedEmployeeListView, ApprovedEmployeeListView, \
    SeparatedEmployeesListView, RejectedEmployeeListView, EmployeeBirthdayList, AssignProjectListView, \
    CostCentreCreate, CostCentreUpdate, CostCentreDetailView, CostCentreListView, \
    SOFCreate, SOFUpdate, SOFDetailView, \
    SOFListView, DEACreate, DEAUpdate, DEADetailView, DEAListView, EmployeeProjectsListView, \
    EmployeeProjectsDetailView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryListView, \
    ProjectCreate, ProjectUpdate, ProjectDetailView, ProjectListView, EmployeeProjectCreation, \
    ChangeGroupEmployeeListView, EmployeeMovementsListView, EmployeeMovementsCreate, ApprovedEmployeeMovementsListView, \
    EnumerationsMovementsCreate, EnumEmployeeMovementsListView

app_name = 'users'
urlpatterns = [
    path('new_employee/', views.register_employee, name='new-employee'),
    path('profile/', views.profile, name='user-profile'),
    path('<int:pk>/edit_employee/', views.user_update_profile, name='user-detail'),
    path('new_employee_approval/', RecruitedEmployeeListView.as_view(), name='employee-approval'),
    path('edit_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_approved_employee_list.html'),
         name='edit-employee'),
    path('terminate_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_terminate_employee_list.html'),
         name='terminate-employee-list'),
    path('separated_employees/', SeparatedEmployeesListView.as_view(), name='separated-employee'),
    path('rejected_employees/', RejectedEmployeeListView.as_view(), name='rejected-employee-list'),
    path('employees_birthdays/', EmployeeBirthdayList.as_view(), name='employee-birthday-list'),
    path('reject_employee/<int:pk>/', views.reject_employee, name='reject-employee'),
    path('new_employee_approval/<int:pk>/edit/', views.approve_employee, name='approve-employee'),
    path('payroll_period/<int:pk>/process/', views.process_payroll_period, name='process_payroll-period'),
    path('payroll_period/<int:pk>/process/<int:user>', views.process_payroll_period, name='process_payroll-period'),
    path('terminate_employee/<int:pk>/', views.terminate_employee, name='terminate-employee'),
    path('employee/assign/projects/', AssignProjectListView.as_view(), name='employee-assign-project'),
    path('employee/assign/project/<int:pk>/', EmployeeProjectCreation.as_view(), name='employee-project-creation'),
    path('cost_centres/add/', CostCentreCreate.as_view(), name='cost-centre-create'),
    path('cost_centre/<int:pk>/edit/', CostCentreUpdate.as_view(), name='cost-centre-update'),
    path('cost_centres/', CostCentreListView.as_view(), name='cost-centre-list'),
    path('cost_centre/<int:pk>/', CostCentreDetailView.as_view(), name='cost-centre-detail'),
    path('projects/add/', ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('sof/add/', SOFCreate.as_view(), name='sof-create'),
    path('sof/<int:pk>/edit/', SOFUpdate.as_view(), name='sof-update'),
    path('sof/', SOFListView.as_view(), name='sof-list'),
    path('sof/<int:pk>/', SOFDetailView.as_view(), name='sof-detail'),
    path('dea/add/', DEACreate.as_view(), name='dea-create'),
    path('dea/<int:pk>/edit/', DEAUpdate.as_view(), name='dea-update'),
    path('dea/', DEAListView.as_view(), name='dea-list'),
    path('dea/<int:pk>/', DEADetailView.as_view(), name='dea-detail'),
    path('employee/projects/', EmployeeProjectsListView.as_view(), name='employee-project-list'),
    path('employee/project/<int:pk>', EmployeeProjectsDetailView.as_view(), name='employee-project-detail'),
    path('employee_category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('employee_category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('employee_categories/', CategoryListView.as_view(), name='category_list'),
    path('employee_category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('change_user_group/<int:pk>', views.user_change_group, name='user_change_group'),
    path('change/group/', ChangeGroupEmployeeListView.as_view(), name='change_employee_user_group'),
    path('employee/reactivate/<int:pk>', views.reactivate_employee, name='reactivate_employee'),
    path('employee/', ApprovedEmployeeMovementsListView.as_view(), name='employee_movements'),
    path('employee/movements/', EmployeeMovementsListView.as_view(), name='employee_movements_changelist'),
    path('employee/movements/add/<int:user_id>/<int:requester_id>/', EmployeeMovementsCreate.as_view(), name='employee_movements_add'),
    path('ajax/load_movements/', views.load_movements, name='ajax_load_movements'),
    path('ajax/load_current_param/', views.load_current_param, name='ajax_load_current'),
    path('employee/earnings/movements/add/<int:user_id>/<int:requester_id>/', EnumerationsMovementsCreate.as_view(),
         name='employee_movements_add_enums'),
    path('employee/earning/movements/', EnumEmployeeMovementsListView.as_view(), name='employee_movements_enums'),
    path('ajax/load_earnings/amount/', views.load_earnings_current_amount, name='ajax_load_current_earning'),
    path('approve/movement/<int:movement_id>/', views.approve_employee_movement, name='approve_employee_movement'),
    path('decline/movement/<int:movement_id>/', views.decline_employee_movement, name='decline_employee_movement'),
    path('ajax/load_overtime_factor/factor/', views.load_overtime_factor, name='ajax_load_factor'),
]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.db.models import Q
from django.utils import timezone

from hr_system.constants import YES_OR_NO_TYPES
from payroll.models import EarningDeductionType, PayrollPeriod
from support_data.models import MovementParameter, DutyStation
from .constants import GENDER, EMP_APPROVE_OR_REJECT
from .models import Employee, TerminatedEmployees, CostCentre, SOF, DEA, EmployeeProject, PayrollProcessors, Project, \
    EmployeeMovement


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username", required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password", required=True)


class StaffCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'middle_name',
                  'email', 'password1', 'password2']


class StaffUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'middle_name',
                  'email',
                  )


class ProfileCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_group'].widget.attrs['disabled'] = 'disabled'

    class Meta:
        model = Employee
        fields = '__all__'

    date_of_birth = forms.DateField(input_formats=['%Y-%m-%d'])
    sex = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect(), required=False)
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), widget=forms.Select(), required=False)
    appointment_date = forms.DateField(input_formats=['%Y-%m-%d'], initial=timezone.now(), required=False)
    contract_expiry = forms.DateField(input_formats=['%Y-%m-%d'], required=False)
    social_security = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False,
                                        initial=YES_OR_NO_TYPES[1][0])
    transferable = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False)
    assigned_locations = forms.ModelMultipleChoiceField(queryset=DutyStation.objects.all(),
                                                        widget=forms.CheckboxSelectMultiple(),
                                                        required=False)


class ProfileGroupForm(forms.ModelForm):
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)

    class Meta:
        model = Employee
        fields = ['user_group']

    def save(self, commit=True):
        return super().save(commit)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_group'].widget.attrs['disabled'] = 'disabled'
        self.fields['assigned_locations'].widget.attrs['disabled'] = 'disabled'

    date_of_birth = forms.DateField(input_formats=['%Y-%m-%d'])
    sex = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect(), required=True)
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), widget=forms.Select(), required=False)
    appointment_date = forms.DateField(input_formats=['%Y-%m-%d'], initial=timezone.now(), required=False)
    contract_expiry = forms.DateField(input_formats=['%Y-%m-%d'], required=False)
    social_security = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False,
                                        initial=YES_OR_NO_TYPES[1][0])
    transferable = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False)
    assigned_locations = forms.ModelMultipleChoiceField(queryset=DutyStation.objects.all(),
                                                        widget=forms.CheckboxSelectMultiple(),
                                                        required=False, disabled=True)


class EmployeeApprovalForm(ProfileCreationForm):
    employment_status = forms.ChoiceField(choices=EMP_APPROVE_OR_REJECT, widget=forms.Select(), required=False)

    class Meta:
        model = Employee
        fields = '__all__'


class TerminationForm(forms.ModelForm):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all())
    notice_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        required=False
    )
    exit_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        required=False
    )

    class Meta:
        model = TerminatedEmployees
        fields = '__all__'


class EmployeeProjectForm(forms.ModelForm):
    class Meta:
        model = EmployeeProject
        fields = '__all__'


class CostCentreForm(forms.ModelForm):
    class Meta:
        model = CostCentre
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class SOFForm(forms.ModelForm):
    class Meta:
        model = SOF
        fields = '__all__'


class DEAForm(forms.ModelForm):
    class Meta:
        model = DEA

        fields = '__all__'


class EarningsProcessUpdateForm(forms.ModelForm):
    earning_and_deductions_type = forms.ModelChoiceField(
        queryset=EarningDeductionType.objects.all(),
        widget=forms.Select(
            attrs={
                'style':
                    'border: none; outline: none; text-align: left; margin: 0;' +
                    '-webkit-appearance: none; -moz-appearance: none;' +
                    'text-indent: 1px; text-overflow: \' \'; background-color: transparent;',
            }
        ),
        required=False
    )
    amount = forms.DecimalField(
        required=False,
        widget=forms.NumberInput(
            attrs={'style': 'border: none; outline: none; text-align: right; margin: 0;'}
        ),
        disabled=True
    )

    class Meta:
        model = PayrollProcessors
        exclude = ['employee', 'payroll_period', 'earning_and_deductions_category']


class DeductionsProcessUpdateForm(forms.ModelForm):
    earning_and_deductions_type = forms.ModelChoiceField(
        queryset=EarningDeductionType.objects.all(),
        widget=forms.Select(
            attrs={
                'style':
                    'border: none; outline: none; text-align: left; margin: 0;' +
                    '-webkit-appearance: none; -moz-appearance: none;' +
                    'text-indent: 1px; text-overflow: \' \'; background-color: transparent;',
            }
        ),
        required=False
    )
    amount = forms.DecimalField(
        required=False,
        widget=forms.NumberInput(
            attrs={'style': 'border: none; outline: none; text-align: right; margin: 0;'}
        )
    )

    class Meta:
        model = PayrollProcessors
        exclude = ['employee', 'payroll_period', 'earning_and_deductions_category']


class EmployeeMovementForm(forms.ModelForm):
    class Meta:
        model = EmployeeMovement
        fields = ['employee_name', 'department', 'job_title', 'parameter', 'move_from', 'move_to', 'remarks']

    move_to = forms.CharField(widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parameter'].queryset = MovementParameter.objects.filter(choice__exact=1).all()


class EnumerationsMovementForm(forms.ModelForm):
    class Meta:
        model = EmployeeMovement
        fields = '__all__'

    OVERTIME = (
        ("NORMAL", "Normal"),
        ("WEEKEND", "Weekend"),
    )

    parameter = forms.ModelChoiceField(queryset=MovementParameter.objects.all(), widget=forms.Select())
    earnings = forms.ModelChoiceField(queryset=EarningDeductionType.objects.all(), widget=forms.Select())
    payroll_period = forms.ModelChoiceField(queryset=PayrollPeriod.objects.all(), widget=forms.Select(), required=True)
    hours = forms.FloatField(required=False)
    over_time_category = forms.ChoiceField(choices=OVERTIME, widget=forms.RadioSelect(), required=False)
    move_from = forms.DecimalField(required=False)
    move_to = forms.DecimalField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parameter'].queryset = MovementParameter.objects.filter(choice__exact=2).all()
        self.fields['earnings'].queryset = EarningDeductionType.objects.filter(Q(display_number__lt=7) | Q(pk=78)) \
            .exclude(payrollcentereds__isnull=True).all()
        self.fields['move_to'].label = 'Change amount to'
        self.fields['move_from'].label = 'Change amount from'
        self.fields['payroll_period'].queryset = PayrollPeriod.objects.filter(status='OPEN').all()

templates/users/employees/_approved_employee_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Approved Staff List</h4>
        <div class="table-responsive">
            <p id="date_filter">
                <strong><small><span id="date-label-from"
                                     class="date-label">Appointment From: </span></small></strong><input
                    class="date_range_filter date"
                    type="text" id="datepicker_from" placeholder="dd/mm/yyyy"/>
                <strong><small><span id="date-label-to"
                                     class="date-label">Appointment To: </span></small></strong><input
                    class="date_range_filter date" type="text"
                    id="datepicker_to" placeholder="dd/mm/yyyy"/>
            </p>
            <table id="table_id" class="display table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Approved Staff List</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Full name</th>
                    <th>Date Of Birth</th>
                    <th>Sex</th>
                    <th>Marital status</th>
                    <th>Mobile No.</th>
                    <th>Email</th>
                    <th>ID No.</th>
                    <th>Agresso No.</th>
                    <th>Passport</th>
                    <th>Nationality</th>
                    <th>Home address</th>
                    <th>Residential address</th>
                    <th>State</th>
                    <th>Insurance Category</th>
                    <th>Duty country</th>
                    <th>Duty station</th>
                    <th>Department</th>
                    <th>Job title</th>
                    <th>Reports to</th>
                    <th>Appointment date</th>
                    <th>Contract type</th>
                    <th>Contract expiry</th>
                    <th>Employee category</th>
                    <th>Grade</th>
                    <th>Basic salary</th>
                    <th>Currency</th>
                    <th>TIN No.</th>
                    <th>Social security</th>
                    <th>Social security No.</th>
                    <th>Payroll Center</th>
                    <th>Bank 1</th>
                    <th>A/C 1</th>
                    <th>Bank 1 %age</th>
                    <th>Bank 2</th>
                    <th>A/C 2</th>
                    <th>Bank 2 %age</th>
                    <th>Kin full name</th>
                    <th>Kin phone no.</th>
                    <th>Kin email</th>
                    <th>Relationship</th>
                    <th>DR A/C code</th>
                    <th>CR A/C code</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for employee in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'users:user-detail' pk=employee.pk %}">{{ employee.user.get_full_name }}</a>
                        </td>
                        <td>{{ employee.date_of_birth|date:'d/m/Y' }}</td>
                        <td>{{ employee.sex }}</td>
                        <td>{{ employee.marital_status }}</td>
                        <td>{{ employee.mobile_number }}</td>
                        <td>{{ employee.user.email }}</td>
                        <td>{{ employee.id_number }}</td>
                        <td>{{ employee.agresso_number }}</td>
                        <td>{{ employee.passport_number }}</td>
                        <td>{{ employee.nationality }}</td>
                        <td>{{ employee.home_address }}</td>
                        <td>{{ employee.residential_address }}</td>
                        <td>{{ employee.district }}</td>
                        <td>{{ employee.medical_insurance_category }}</td>
                        <td>{{ employee.duty_country }}</td>
                        <td>{{ employee.duty_station }}</td>
                        <td>{{ employee.department }}</td>
                        <td>{{ employee.job_title }}</td>
                        <td>{{ employee.line_manager }}</td>
                        <td>{{ employee.appointment_date|date:'d M, Y' }}</td>
                        <td>{{ employee.contract_type }}</td>
                        <td>{{ employee.contract_expiry }}</td>
                        <td>{{ employee.category }}</td>
                        <td>{{ employee.grade }}</td>
                        <td>{{ employee.basic_salary|intcomma }}</td>
                        <td>{{ employee.currency }}</td>
                        <td>{{ employee.tin_number }}</td>
                        <td>{{ employee.social_security }}</td>
                        <td>{{ employee.social_security_number }}</td>
                        <td>{{ employee.payroll_center }}</td>
                        <td>{{ employee.bank_1 }}</td>
                        <td>{{ employee.first_account_number }}</td>
                        <td>{{ employee.first_bank_percentage }}</td>
                        <td>{{ employee.bank_2 }}</td>
                        <td>{{ employee.second_account_number }}</td>
                        <td>{{ employee.second_bank_percentage }}</td>
                        <td>{{ employee.kin_full_name }}</td>
                        <td>{{ employee.kin_phone_number }}</td>
                        <td>{{ employee.kin_email }}</td>
                        <td>{{ employee.kin_relationship }}</td>
                        <td>{{ employee.dr_ac_code }}</td>
                        <td>{{ employee.cr_ac_code }}</td>
                        <td class="text-success">{{ employee.employment_status }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        // Date range filter
        minDateFilter = "";
        maxDateFilter = "";

        $.fn.dataTableExt.afnFiltering.push(
            function (oSettings, aData, iDataIndex) {
                if (typeof aData._date == 'undefined') {
                    aData._date = new Date(aData[18]).getTime();
                }

                if (minDateFilter && !isNaN(minDateFilter)) {
                    if (aData._date < minDateFilter) {
                        return false;
                    }
                }

                if (maxDateFilter && !isNaN(maxDateFilter)) {
                    if (aData._date > maxDateFilter) {
                        return false;
                    }
                }

                return true;
            }
        );

        $(document).ready(function () {
            let editEmployeeTable = $('#table_id').DataTable({
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                        pageSize: 'A1',
                    },
                    'print'
                ]
            });


            $("#datepicker_from").datepicker({
                showOn: "button",
                buttonImage: "https://www.w3resource.com/w3r_images/datepicker2.png",
                buttonImageOnly: false,
                "onSelect": function (date) {
                    minDateFilter = new Date(date).getTime();
                    editEmployeeTable.draw();
                }
            }).keyup(function () {
                minDateFilter = new Date(this.value).getTime();
                editEmployeeTable.draw();
            });

            $("#datepicker_to").datepicker({
                showOn: "button",
                buttonImage: "https://www.w3resource.com/w3r_images/datepicker2.png",
                buttonImageOnly: false,
                "onSelect": function (date) {
                    maxDateFilter = new Date(date).getTime();
                    editEmployeeTable.draw();
                }
            }).keyup(function () {
                maxDateFilter = new Date(this.value).getTime();
                editEmployeeTable.draw();
            });
        });
    </script>
{% endblock scripts %}

templates/users/employees/_terminate_employee_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Terminate Employee</legend>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.employee|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.days_given|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.reason_for_exit|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.notice_date|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.exit_date|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.employable|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.liked_most|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.liked_least|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.change|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.reason_for_coming_back|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.recommend_org|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.reason_for_no|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.rating|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'users:user-detail' employee.pk %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(function () {
            $("#id_notice_date").datetimepicker({
                format: 'Y-m-d',
            });
            $("#id_exit_date").datetimepicker({
                format: 'Y-m-d',
            });
        });
    </script>
{% endblock scripts %}

templates/users/employees/_terminate_employee_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <h4 class="border-bottom mb-4">Terminate Employee</h4>
        <div class="table-responsive">
            <table id="table_id" class="display table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Terminate Employee</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Job Title</th>
                    <th>ID Number</th>
                    <th>Email</th>
                    <th>Mobile No</th>
                    <th>Department</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for employee in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'users:user-detail' pk=employee.pk %}">{{ employee.user.get_full_name }}</a>
                        </td>
                        <td>{{ employee.job_title }}</td>
                        <td>{{ employee.id_number }}</td>
                        <td>{{ employee.user.email }}</td>
                        <td>{{ employee.mobile_number }}</td>
                        <td>{{ employee.department }}</td>
                        <td>
                            <a class="btn btn-sm btn-danger" href="{% url 'users:terminate-employee' pk=employee.pk %}">
                                TERMINATE
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}