hr_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views

admin.AdminSite.site_header = 'Payroll System Administration'
admin.AdminSite.site_title = 'Payroll System Admin'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('logout_reset/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_RESET_REDIRECT_URL), name='reset_logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/auth/password_reset.html',
                                              email_template_name='users/auth/password_reset_email.html'),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/auth/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/auth/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('payroll.urls')),
    path('users/', include('users.urls')),
    path('support_data/', include('support_data.urls')),
    path('admin/', views.login_admin),
    path('admin/payroll/', admin.site.urls),
    path('reports/', include('reports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

users/urls.py
from django.urls import path

from . import views
from .views import RecruitedEmployeeListView, ApprovedEmployeeListView, \
    SeparatedEmployeesListView, RejectedEmployeeListView, EmployeeBirthdayList, AssignProjectListView, \
    CostCentreCreate, CostCentreUpdate, CostCentreDetailView, CostCentreListView, \
    SOFCreate, SOFUpdate, SOFDetailView, \
    SOFListView, DEACreate, DEAUpdate, DEADetailView, DEAListView, EmployeeProjectsListView, \
    EmployeeProjectsDetailView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryListView, \
    ProjectCreate, ProjectUpdate, ProjectDetailView, ProjectListView, EmployeeProjectCreation, \
    ChangeGroupEmployeeListView, EmployeeMovementsListView, EmployeeMovementsCreate, ApprovedEmployeeMovementsListView, \
    EnumerationsMovementsCreate, EnumEmployeeMovementsListView

app_name = 'users'
urlpatterns = [
    path('new_employee/', views.register_employee, name='new-employee'),
    path('profile/', views.profile, name='user-profile'),
    path('<int:pk>/edit_employee/', views.user_update_profile, name='user-detail'),
    path('new_employee_approval/', RecruitedEmployeeListView.as_view(), name='employee-approval'),
    path('edit_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_approved_employee_list.html'),
         name='edit-employee'),
    path('terminate_employee/',
         ApprovedEmployeeListView.as_view(template_name='users/employees/_terminate_employee_list.html'),
         name='terminate-employee-list'),
    path('separated_employees/', SeparatedEmployeesListView.as_view(), name='separated-employee'),
    path('rejected_employees/', RejectedEmployeeListView.as_view(), name='rejected-employee-list'),
    path('employees_birthdays/', EmployeeBirthdayList.as_view(), name='employee-birthday-list'),
    path('reject_employee/<int:pk>/', views.reject_employee, name='reject-employee'),
    path('new_employee_approval/<int:pk>/edit/', views.approve_employee, name='approve-employee'),
    path('payroll_period/<int:pk>/process/', views.process_payroll_period, name='process_payroll-period'),
    path('payroll_period/<int:pk>/process/<int:user>', views.process_payroll_period, name='process_payroll-period'),
    path('terminate_employee/<int:pk>/', views.terminate_employee, name='terminate-employee'),
    path('employee/assign/projects/', AssignProjectListView.as_view(), name='employee-assign-project'),
    path('employee/assign/project/<int:pk>/', EmployeeProjectCreation.as_view(), name='employee-project-creation'),
    path('cost_centres/add/', CostCentreCreate.as_view(), name='cost-centre-create'),
    path('cost_centre/<int:pk>/edit/', CostCentreUpdate.as_view(), name='cost-centre-update'),
    path('cost_centres/', CostCentreListView.as_view(), name='cost-centre-list'),
    path('cost_centre/<int:pk>/', CostCentreDetailView.as_view(), name='cost-centre-detail'),
    path('projects/add/', ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('sof/add/', SOFCreate.as_view(), name='sof-create'),
    path('sof/<int:pk>/edit/', SOFUpdate.as_view(), name='sof-update'),
    path('sof/', SOFListView.as_view(), name='sof-list'),
    path('sof/<int:pk>/', SOFDetailView.as_view(), name='sof-detail'),
    path('dea/add/', DEACreate.as_view(), name='dea-create'),
    path('dea/<int:pk>/edit/', DEAUpdate.as_view(), name='dea-update'),
    path('dea/', DEAListView.as_view(), name='dea-list'),
    path('dea/<int:pk>/', DEADetailView.as_view(), name='dea-detail'),
    path('employee/projects/', EmployeeProjectsListView.as_view(), name='employee-project-list'),
    path('employee/project/<int:pk>', EmployeeProjectsDetailView.as_view(), name='employee-project-detail'),
    path('employee_category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('employee_category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('employee_categories/', CategoryListView.as_view(), name='category_list'),
    path('employee_category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('change_user_group/<int:pk>', views.user_change_group, name='user_change_group'),
    path('change/group/', ChangeGroupEmployeeListView.as_view(), name='change_employee_user_group'),
    path('employee/reactivate/<int:pk>', views.reactivate_employee, name='reactivate_employee'),
    path('employee/', ApprovedEmployeeMovementsListView.as_view(), name='employee_movements'),
    path('employee/movements/', EmployeeMovementsListView.as_view(), name='employee_movements_changelist'),
    path('employee/movements/add/<int:user_id>/<int:requester_id>/', EmployeeMovementsCreate.as_view(), name='employee_movements_add'),
    path('ajax/load_movements/', views.load_movements, name='ajax_load_movements'),
    path('ajax/load_current_param/', views.load_current_param, name='ajax_load_current'),
    path('employee/earnings/movements/add/<int:user_id>/<int:requester_id>/', EnumerationsMovementsCreate.as_view(),
         name='employee_movements_add_enums'),
    path('employee/earning/movements/', EnumEmployeeMovementsListView.as_view(), name='employee_movements_enums'),
    path('ajax/load_earnings/amount/', views.load_earnings_current_amount, name='ajax_load_current_earning'),
    path('approve/movement/<int:movement_id>/', views.approve_employee_movement, name='approve_employee_movement'),
    path('decline/movement/<int:movement_id>/', views.decline_employee_movement, name='decline_employee_movement'),
    path('ajax/load_overtime_factor/factor/', views.load_overtime_factor, name='ajax_load_factor'),
]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.db.models import Q
from django.utils import timezone

from hr_system.constants import YES_OR_NO_TYPES
from payroll.models import EarningDeductionType, PayrollPeriod
from support_data.models import MovementParameter, DutyStation
from .constants import GENDER, EMP_APPROVE_OR_REJECT
from .models import Employee, TerminatedEmployees, CostCentre, SOF, DEA, EmployeeProject, PayrollProcessors, Project, \
    EmployeeMovement


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username", required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password", required=True)


class StaffCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'middle_name',
                  'email', 'password1', 'password2']


class StaffUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'middle_name',
                  'email',
                  )


class ProfileCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_group'].widget.attrs['disabled'] = 'disabled'

    class Meta:
        model = Employee
        fields = '__all__'

    date_of_birth = forms.DateField(input_formats=['%Y-%m-%d'])
    sex = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect(), required=False)
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), widget=forms.Select(), required=False)
    appointment_date = forms.DateField(input_formats=['%Y-%m-%d'], initial=timezone.now(), required=False)
    contract_expiry = forms.DateField(input_formats=['%Y-%m-%d'], required=False)
    social_security = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False,
                                        initial=YES_OR_NO_TYPES[1][0])
    transferable = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False)
    assigned_locations = forms.ModelMultipleChoiceField(queryset=DutyStation.objects.all(),
                                                        widget=forms.CheckboxSelectMultiple(),
                                                        required=False)


class ProfileGroupForm(forms.ModelForm):
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)

    class Meta:
        model = Employee
        fields = ['user_group']

    def save(self, commit=True):
        return super().save(commit)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_group'].widget.attrs['disabled'] = 'disabled'
        self.fields['assigned_locations'].widget.attrs['disabled'] = 'disabled'

    date_of_birth = forms.DateField(input_formats=['%Y-%m-%d'])
    sex = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect(), required=True)
    user_group = forms.ModelChoiceField(queryset=Group.objects.all(), widget=forms.Select(), required=False)
    appointment_date = forms.DateField(input_formats=['%Y-%m-%d'], initial=timezone.now(), required=False)
    contract_expiry = forms.DateField(input_formats=['%Y-%m-%d'], required=False)
    social_security = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False,
                                        initial=YES_OR_NO_TYPES[1][0])
    transferable = forms.ChoiceField(choices=YES_OR_NO_TYPES, widget=forms.RadioSelect(), required=False)
    assigned_locations = forms.ModelMultipleChoiceField(queryset=DutyStation.objects.all(),
                                                        widget=forms.CheckboxSelectMultiple(),
                                                        required=False, disabled=True)


class EmployeeApprovalForm(ProfileCreationForm):
    employment_status = forms.ChoiceField(choices=EMP_APPROVE_OR_REJECT, widget=forms.Select(), required=False)

    class Meta:
        model = Employee
        fields = '__all__'


class TerminationForm(forms.ModelForm):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all())
    notice_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        required=False
    )
    exit_date = forms.DateField(
        input_formats=['%Y-%m-%d'],
        required=False
    )

    class Meta:
        model = TerminatedEmployees
        fields = '__all__'


class EmployeeProjectForm(forms.ModelForm):
    class Meta:
        model = EmployeeProject
        fields = '__all__'


class CostCentreForm(forms.ModelForm):
    class Meta:
        model = CostCentre
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class SOFForm(forms.ModelForm):
    class Meta:
        model = SOF
        fields = '__all__'


class DEAForm(forms.ModelForm):
    class Meta:
        model = DEA

        fields = '__all__'


class EarningsProcessUpdateForm(forms.ModelForm):
    earning_and_deductions_type = forms.ModelChoiceField(
        queryset=EarningDeductionType.objects.all(),
        widget=forms.Select(
            attrs={
                'style':
                    'border: none; outline: none; text-align: left; margin: 0;' +
                    '-webkit-appearance: none; -moz-appearance: none;' +
                    'text-indent: 1px; text-overflow: \' \'; background-color: transparent;',
            }
        ),
        required=False
    )
    amount = forms.DecimalField(
        required=False,
        widget=forms.NumberInput(
            attrs={'style': 'border: none; outline: none; text-align: right; margin: 0;'}
        ),
        disabled=True
    )

    class Meta:
        model = PayrollProcessors
        exclude = ['employee', 'payroll_period', 'earning_and_deductions_category']


class DeductionsProcessUpdateForm(forms.ModelForm):
    earning_and_deductions_type = forms.ModelChoiceField(
        queryset=EarningDeductionType.objects.all(),
        widget=forms.Select(
            attrs={
                'style':
                    'border: none; outline: none; text-align: left; margin: 0;' +
                    '-webkit-appearance: none; -moz-appearance: none;' +
                    'text-indent: 1px; text-overflow: \' \'; background-color: transparent;',
            }
        ),
        required=False
    )
    amount = forms.DecimalField(
        required=False,
        widget=forms.NumberInput(
            attrs={'style': 'border: none; outline: none; text-align: right; margin: 0;'}
        )
    )

    class Meta:
        model = PayrollProcessors
        exclude = ['employee', 'payroll_period', 'earning_and_deductions_category']


class EmployeeMovementForm(forms.ModelForm):
    class Meta:
        model = EmployeeMovement
        fields = ['employee_name', 'department', 'job_title', 'parameter', 'move_from', 'move_to', 'remarks']

    move_to = forms.CharField(widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parameter'].queryset = MovementParameter.objects.filter(choice__exact=1).all()


class EnumerationsMovementForm(forms.ModelForm):
    class Meta:
        model = EmployeeMovement
        fields = '__all__'

    OVERTIME = (
        ("NORMAL", "Normal"),
        ("WEEKEND", "Weekend"),
    )

    parameter = forms.ModelChoiceField(queryset=MovementParameter.objects.all(), widget=forms.Select())
    earnings = forms.ModelChoiceField(queryset=EarningDeductionType.objects.all(), widget=forms.Select())
    payroll_period = forms.ModelChoiceField(queryset=PayrollPeriod.objects.all(), widget=forms.Select(), required=True)
    hours = forms.FloatField(required=False)
    over_time_category = forms.ChoiceField(choices=OVERTIME, widget=forms.RadioSelect(), required=False)
    move_from = forms.DecimalField(required=False)
    move_to = forms.DecimalField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parameter'].queryset = MovementParameter.objects.filter(choice__exact=2).all()
        self.fields['earnings'].queryset = EarningDeductionType.objects.filter(Q(display_number__lt=7) | Q(pk=78)) \
            .exclude(payrollcentereds__isnull=True).all()
        self.fields['move_to'].label = 'Change amount to'
        self.fields['move_from'].label = 'Change amount from'
        self.fields['payroll_period'].queryset = PayrollPeriod.objects.filter(status='OPEN').all()

templates/users/employeemovement_earnings_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form id="movementsForm" method="POST" data-user="{{ user_id }}"
              data-movement-url="{% url 'users:ajax_load_movements' %}"
              data-current-url="{% url 'users:ajax_load_current' %}">
            {% csrf_token %}

            <div class="form-group">
                {{ form|crispy }}
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'users:employee_movements_changelist' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        $("#id_parameter").change(function () {
            let form = $("#movementsForm");
            let url = form.attr('data-movement-url');
            let user_id = form.attr('data-user');
            let current_param = form.attr('data-current-url');
            console.log(url);
            let parameter_id = $(this).val();

            $.ajax({
                url: current_param,
                data: {
                    'parameter': parameter_id,
                    'user_id': user_id
                },
                success: function (data) {
                    console.log("Serial data: " + data['movements_from']);
                    $("#id_move_from").val(data['movements_from']);
                }
            });

            $.ajax({
                url: url,
                data: {
                    'parameter': parameter_id
                },
                success: function (data) {
                    $("#id_move_to").html(data);
                }
            });
        })
    </script>
{% endblock scripts %}

templates/users/employeemovement_earnings_form_enums.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form id="movementsForm" method="POST" data-user="{{ user_id }}"
              data-movement-url="{% url 'users:ajax_load_current_earning' %}"
              data-overtime-url="{% url 'users:ajax_load_factor' %}">
            {% csrf_token %}

            <div class="form-group">
                {{ form|crispy }}
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'users:employee_movements_enums' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        const div_working_days = $("#div_id_hours");
        const div_overtime = $("#div_id_over_time_category");
        div_working_days.css("display", "none");
        div_overtime.css("display", "none");

        const form = $("#movementsForm");
        const url = form.attr('data-movement-url');
        const overtime_url = form.attr("data-overtime-url");

        const amount_from = $("#id_move_from");
        amount_from.prop("readonly", true);


        $("#id_earnings").change(function () {
            const amount_to = $("#id_move_to");
            const user_id = form.attr('data-user');
            const earnings_id = $(this).val();

            const hour_input = $("#id_hours");

            const periodInput = $("#id_payroll_period");
            const radio_overtime_input = $(':radio[name="over_time_category"]');

            periodInput.prop("selectedIndex", -1);
            amount_from.val("");
            amount_to.val("");

            if (parseInt(earnings_id) === 1) {
                console.log("earning 1");
                amount_to.prop("readonly", false);
                div_overtime.css("display", "none");
                div_working_days.css("display", "none");
                periodInput.change(function () {
                    let period_id = $(this).val();
                    let data = {};
                    data['period'] = period_id;
                    data['parameter'] = earnings_id;
                    data['user_id'] = user_id;
                    console.log("data: ");
                    console.log(data);
                    if (period_id > 0 && period_id != null) {
                        $.ajax({
                            url: url,
                            data: data,
                            success: function (response) {
                                console.log("response: ");
                                console.log(response);
                                setUp(response)
                            }
                        });
                    }

                    function setUp(response) {
                        amount_from.val(response['amount']);
                    }
                });
            } else if (parseInt(earnings_id) === 78) {
                console.log("earning 78");
                $("label[for='id_hours']").text("Working days");
                div_working_days.css("display", "block");
                div_overtime.css("display", "none");
                amount_to.prop("readonly", true);
                hour_input.prop("required", true);
                let working_days = 0;
                periodInput.change(function () {
                    let period_id = $(this).val();
                    let data = {};
                    data['period'] = period_id;
                    data['parameter'] = earnings_id;
                    data['user_id'] = user_id;
                    console.log("data: ");
                    console.log(data);
                    if (period_id > 0 && period_id != null) {
                        $.ajax({
                            url: url,
                            data: data,
                            success: function (response) {
                                console.log("response: ");
                                console.log(response);
                                setUp(response)
                            }
                        });
                    }

                    function setUp(response) {
                        working_days = parseFloat(response['working_days']);
                        console.log("working days: " + working_days);
                        amount_from.val(response['amount']);
                        console.log("basic salary: " + response['amount']);
                        let newAmt = (parseFloat(response['working_days']) / 22.0) * parseFloat(response['amount']);
                        hour_input.val(response['working_days']);
                        console.log("New amount: " + newAmt);
                        amount_to.val(newAmt);
                    }
                });
                hour_input.on("keyup", function () {
                    let currentValue = $(this).val();
                    let newAmt = (currentValue / 22.0) * amount_from.val();
                    amount_to.val(newAmt);
                });
                div_working_days.css("display", "block");
            } else if (parseInt(earnings_id) === 8) {
                console.log("earning 8");
                div_overtime.css("display", "block");
                div_working_days.css("display", "block");
                periodInput.change(function () {
                    let period_id = $(this).val();
                    let data = {};
                    data['period'] = period_id;
                    data['parameter'] = earnings_id;
                    data['user_id'] = user_id;
                    console.log("data: ");
                    console.log(data);
                    if (period_id > 0 && period_id != null) {
                        $.ajax({
                            url: url,
                            data: data,
                            success: function (response) {
                                console.log(response);
                                setUp(response)
                            }
                        });
                    }

                    function setUp(response) {
                        amount_from.val(response['amount']);
                    }
                });

                radio_overtime_input.change(function () {
                    const value = $(this).filter(":checked").val();
                    console.log(value);
                    let dataToSend = {
                        "overtime_type": value,
                        "period_id": periodInput.val(),
                        "user_id": user_id,
                        "hours": hour_input.val()
                    };

                    function setUpMoveToAmt(response) {
                        amount_to.val(response["overtime_amount"])
                    }

                    $.ajax({
                        url: overtime_url,
                        data: dataToSend,
                        success: function (response) {
                            console.log(response);
                            setUpMoveToAmt(response)
                        }
                    });
                });

            } else {
                console.log("earning other");
                amount_to.prop("readonly", false);
                div_working_days.css("display", "none");
                div_overtime.css("display", "none");
                periodInput.change(function () {
                    let period_id = $(this).val();
                    let data = {};
                    data['period'] = period_id;
                    data['parameter'] = earnings_id;
                    data['user_id'] = user_id;
                    console.log("data: ");
                    console.log(data);
                    if (period_id > 0 && period_id != null) {
                        $.ajax({
                            url: url,
                            data: data,
                            success: function (response) {
                                console.log(response);
                                setUp(response)
                            }
                        });
                    }

                    function setUp(response) {
                        amount_from.val(response['amount']);
                    }
                });
            }

        })
    </script>
{% endblock scripts %}

templates/users/employeemovement_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="content-section">
        <form id="movementsForm" method="POST" data-user="{{ user_id }}"
              data-movement-url="{% url 'users:ajax_load_movements' %}"
              data-current-url="{% url 'users:ajax_load_current' %}">
            {% csrf_token %}

            <div class="form-group">
                {{ form|crispy }}
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-danger" href="{% url 'users:employee_movements_changelist' %}">CANCEL</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        $("#id_parameter").change(function () {
            let form = $("#movementsForm");
            let url = form.attr('data-movement-url');
            let user_id = form.attr('data-user');
            let current_param = form.attr('data-current-url');
            console.log(url);
            let parameter_id = $(this).val();

            $.ajax({
                url: current_param,
                data: {
                    'parameter': parameter_id,
                    'user_id': user_id
                },
                success: function (data) {
                    console.log("Serial data: " + data['movements_from']);
                    $("#id_move_from").val(data['movements_from']);
                }
            });

            $.ajax({
                url: url,
                data: {
                    'parameter': parameter_id
                },
                success: function (data) {
                    $("#id_move_to").html(data);
                }
            });
        })
    </script>
{% endblock scripts %}

templates/users/employeemovement_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <h3 class="border-bottom mb-4">Employee Movements To Approve</h3>
        <div class="table-responsive-md">
            <table id="table_id" class="table table-sm table-striped table-bordered w-100">
                <caption class="border-bottom mb-4">Employee Movements</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Employee</th>
                    <th>Parameter</th>
                    <th>Earning</th>
                    <th>Change From</th>
                    <th>Change To</th>
                    <th>Remarks</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for movement in object_list %}
                    <tr>
                        <td>{{ movement.employee.user.get_full_name }}</td>
                        <td>{{ movement.parameter }}</td>
                        {% if movement.earnings %}
                            <td>{{ movement.earnings }}</td>
                        {% else %}
                            <td>N/A</td>
                        {% endif %}
                        <td>{{ movement.move_from }}</td>
                        <td>{{ movement.move_to }}</td>
                        <td>{{ movement.remarks}}</td>
                        <td>{{ movement.date }}</td>
                        <td class="d-flex justify-content-between">
                            <a class="btn btn-success btn-sm" href="{% url 'users:approve_employee_movement' movement_id=movement.pk %}">Approve</a>
                            <a class="btn btn-danger" href="{% url 'users:decline_employee_movement' movement_id=movement.pk %}">Decline</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#table_id').DataTable( {
                dom: 'lBfrtip',
                scrollX: true,
                scrollCollapse: true,
                autoWidth: true,
                paging: true,
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                    },
                    'print'
                ]
            } );
        } );
    </script>
{% endblock scripts %}

templates/users/movements_dropdown_list_options.html
<option value="">------------</option>
{% for movement in movements_to %}
    <option value="{{ movement }}">{{ movement }}</option>
{% endfor %}